name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
#CUSTOM_DOMAIN = "libcuda.so"
CUSTOM_DOMAIN = "fusen.work"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
   { pattern = "docker.fusen.work", custom_domain = true },
   { pattern = "quay.fusen.work", custom_domain = true },
   { pattern = "gcr.fusen.work", custom_domain = true },
   { pattern = "k8s-gcr.fusen.work", custom_domain = true },
   { pattern = "k8s.fusen.work", custom_domain = true },
   { pattern = "ghcr.fusen.work", custom_domain = true },
   { pattern = "cloudsmith.fusen.work", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.fusen.work", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
